export const VIDEOS_FETCH_SUCCEED = 'videos/FETCH_SUCCEED';
export const VIDEOS_FETCH_REQUESTED = 'videos/FETCH_REQUEST';
export const VIDEOS_FETCH_FAILED = 'videos/FETCH_FAIL';
export const VIEWER_FETCH_REQUESTED = 'videos/VIEWER_FETCH_REQUESTED';
export const VIEWER_FETCH_SUCCEED = 'videos/VIEWER_FETCH_SUCCEED';
export const VIDEOS_RESET_META = 'videos/VIDEOS_RESET_META';
export const RECEIVE_START_TIME = 'videos/ACTUAL_START_TIME';
